// Licensed Materials - Property of IBM
// (c) Copyright IBM Corporation 2018. All Rights Reserved.
// Note to U.S. Government Users Restricted Rights:
// Use, duplication or disclosure restricted by GSA ADP Schedule
// Contract with IBM Corp.

// Code generated by client-gen. DO NOT EDIT.

package clientset

import (
	mcmv1alpha1 "github.ibm.com/IBMPrivateCloud/multicloud-operators-foundation/pkg/client/clientset_generated/clientset/typed/mcm/v1alpha1"
	mcmv1beta1 "github.ibm.com/IBMPrivateCloud/multicloud-operators-foundation/pkg/client/clientset_generated/clientset/typed/mcm/v1beta1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	McmV1alpha1() mcmv1alpha1.McmV1alpha1Interface
	McmV1beta1() mcmv1beta1.McmV1beta1Interface
	// Deprecated: please explicitly pick a version if possible.
	Mcm() mcmv1beta1.McmV1beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	mcmV1alpha1 *mcmv1alpha1.McmV1alpha1Client
	mcmV1beta1  *mcmv1beta1.McmV1beta1Client
}

// McmV1alpha1 retrieves the McmV1alpha1Client
func (c *Clientset) McmV1alpha1() mcmv1alpha1.McmV1alpha1Interface {
	return c.mcmV1alpha1
}

// McmV1beta1 retrieves the McmV1beta1Client
func (c *Clientset) McmV1beta1() mcmv1beta1.McmV1beta1Interface {
	return c.mcmV1beta1
}

// Deprecated: Mcm retrieves the default version of McmClient.
// Please explicitly pick a version.
func (c *Clientset) Mcm() mcmv1beta1.McmV1beta1Interface {
	return c.mcmV1beta1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.mcmV1alpha1, err = mcmv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.mcmV1beta1, err = mcmv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.mcmV1alpha1 = mcmv1alpha1.NewForConfigOrDie(c)
	cs.mcmV1beta1 = mcmv1beta1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.mcmV1alpha1 = mcmv1alpha1.New(c)
	cs.mcmV1beta1 = mcmv1beta1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
