// Licensed Materials - Property of IBM
// (c) Copyright IBM Corporation 2018. All Rights Reserved.
// Note to U.S. Government Users Restricted Rights:
// Use, duplication or disclosure restricted by GSA ADP Schedule
// Contract with IBM Corp.

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

// ClusterJoinRequestListerExpansion allows custom methods to be added to
// ClusterJoinRequestLister.
type ClusterJoinRequestListerExpansion interface{}

// ClusterStatusListerExpansion allows custom methods to be added to
// ClusterStatusLister.
type ClusterStatusListerExpansion interface{}

// ClusterStatusNamespaceListerExpansion allows custom methods to be added to
// ClusterStatusNamespaceLister.
type ClusterStatusNamespaceListerExpansion interface{}

// PlacementBindingListerExpansion allows custom methods to be added to
// PlacementBindingLister.
type PlacementBindingListerExpansion interface{}

// PlacementBindingNamespaceListerExpansion allows custom methods to be added to
// PlacementBindingNamespaceLister.
type PlacementBindingNamespaceListerExpansion interface{}

// PlacementPolicyListerExpansion allows custom methods to be added to
// PlacementPolicyLister.
type PlacementPolicyListerExpansion interface{}

// PlacementPolicyNamespaceListerExpansion allows custom methods to be added to
// PlacementPolicyNamespaceLister.
type PlacementPolicyNamespaceListerExpansion interface{}

// ResourceViewListerExpansion allows custom methods to be added to
// ResourceViewLister.
type ResourceViewListerExpansion interface{}

// ResourceViewNamespaceListerExpansion allows custom methods to be added to
// ResourceViewNamespaceLister.
type ResourceViewNamespaceListerExpansion interface{}

// WorkListerExpansion allows custom methods to be added to
// WorkLister.
type WorkListerExpansion interface{}

// WorkNamespaceListerExpansion allows custom methods to be added to
// WorkNamespaceLister.
type WorkNamespaceListerExpansion interface{}

// WorkSetListerExpansion allows custom methods to be added to
// WorkSetLister.
type WorkSetListerExpansion interface{}

// WorkSetNamespaceListerExpansion allows custom methods to be added to
// WorkSetNamespaceLister.
type WorkSetNamespaceListerExpansion interface{}
