{{- if ne .Values.installMode "Hosted" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if eq .Release.Namespace "open-cluster-management-agent-addon" }}
  name: {{ .Values.org }}:{{ template "work-manager.fullname" . }}-log
  {{- else }}
  name: {{ .Values.org }}:{{ template "work-manager.fullname" . }}-log:{{ .Release.Namespace }}
  {{- end }}
  labels:
    component: "work-manager"
    addon.open-cluster-management.io/hosted-manifest-location: none
subjects:
- kind: ServiceAccount
  name: {{ template "work-manager.fullname" . }}-log
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ template "work-manager.fullname" . }}-log
  apiGroup: rbac.authorization.k8s.io
{{- end }}
