---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: "work-manager"
    addon.open-cluster-management.io/hosted-manifest-location: hosting
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "update", "watch", "patch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes", "routes/custom-host"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["config.openshift.io"]
  resources: ["ingresses"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments","deployments/finalizers"]
  verbs: ["get", "create", "update", "delete"]
