---
{{- if not (eq .Values.clusterName "local-cluster") }}
{{- if eq .Values.product "OpenShift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: "work-manager"
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
  host: ""
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ template "work-manager.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
{{- end }}
