---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: "work-manager"
    addon.open-cluster-management.io/hosted-manifest-location: hosting
