---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: "work-manager"
spec:
{{- if .Values.isOCP }}
  type: LoadBalancer
{{- end }}
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    component: "work-manager"
