---
{{- if not (eq .Values.product "") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: "work-manager"
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
{{- if not (eq .Values.product "OpenShift") }}
  type: LoadBalancer
{{- end }}
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    component: "work-manager"
{{- end }}
