kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocm-controller
  namespace: open-cluster-management
  labels:
    app: ocm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocm-controller
  template:
    metadata:
      labels:
        app: ocm-controller
    spec:
      serviceAccountName: ocm-foundation-sa
      containers:
        - name: ocm-controller
          image: quay.io/stolostron/multicloud-manager
          imagePullPolicy: Always
          args:
            - "/controller"
            - "--enable-agent-deploy=true"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
