// Licensed Materials - Property of IBM
// (c) Copyright IBM Corporation 2018. All Rights Reserved.
// Note to U.S. Government Users Restricted Rights:
// Use, duplication or disclosure restricted by GSA ADP Schedule
// Contract with IBM Corp.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.ibm.com/IBMPrivateCloud/multicloud-operators-foundation/pkg/apis/mcm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkSets implements WorkSetInterface
type FakeWorkSets struct {
	Fake *FakeMcmV1alpha1
	ns   string
}

var worksetsResource = schema.GroupVersionResource{Group: "mcm.ibm.com", Version: "v1alpha1", Resource: "worksets"}

var worksetsKind = schema.GroupVersionKind{Group: "mcm.ibm.com", Version: "v1alpha1", Kind: "WorkSet"}

// Get takes name of the workSet, and returns the corresponding workSet object, and an error if there is any.
func (c *FakeWorkSets) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(worksetsResource, c.ns, name), &v1alpha1.WorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkSet), err
}

// List takes label and field selectors, and returns the list of WorkSets that match those selectors.
func (c *FakeWorkSets) List(opts v1.ListOptions) (result *v1alpha1.WorkSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(worksetsResource, worksetsKind, c.ns, opts), &v1alpha1.WorkSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkSetList{ListMeta: obj.(*v1alpha1.WorkSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workSets.
func (c *FakeWorkSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(worksetsResource, c.ns, opts))

}

// Create takes the representation of a workSet and creates it.  Returns the server's representation of the workSet, and an error, if there is any.
func (c *FakeWorkSets) Create(workSet *v1alpha1.WorkSet) (result *v1alpha1.WorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(worksetsResource, c.ns, workSet), &v1alpha1.WorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkSet), err
}

// Update takes the representation of a workSet and updates it. Returns the server's representation of the workSet, and an error, if there is any.
func (c *FakeWorkSets) Update(workSet *v1alpha1.WorkSet) (result *v1alpha1.WorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(worksetsResource, c.ns, workSet), &v1alpha1.WorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkSets) UpdateStatus(workSet *v1alpha1.WorkSet) (*v1alpha1.WorkSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(worksetsResource, "status", c.ns, workSet), &v1alpha1.WorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkSet), err
}

// Delete takes name of the workSet and deletes it. Returns an error if one occurs.
func (c *FakeWorkSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(worksetsResource, c.ns, name), &v1alpha1.WorkSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(worksetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkSetList{})
	return err
}

// Patch applies the patch and returns the patched workSet.
func (c *FakeWorkSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(worksetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkSet), err
}
