kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocm-proxyserver
  namespace: open-cluster-management
  labels:
    app: ocm-proxyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocm-proxyserver
  template:
    metadata:
      labels:
        app: ocm-proxyserver
    spec:
      serviceAccountName: ocm-foundation-sa
      containers:
        - name: ocm-proxyserver
          image: quay.io/stolostron/multicloud-manager
          imagePullPolicy: Always
          args:
            - "/proxyserver"
            - "--secure-port=6443"
            - "--tls-cert-file=/var/run/apiservice/tls.crt"
            - "--tls-private-key-file=/var/run/apiservice/tls.key"
            - "--proxy-service-cafile=/var/run/clusterproxy/service-ca.crt"
            - "--proxy-service-name=cluster-proxy-addon-user"
            - "--proxy-service-port=9092"
          volumeMounts:
            - mountPath: /var/run/apiservice
              name: apiservice-certs
            - mountPath: /var/run/clusterproxy
              name: cluster-proxy-service-ca
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 6443
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 6443
            initialDelaySeconds: 2
      volumes:
        - name: apiservice-certs
          secret:
            defaultMode: 420
            secretName: ocm-proxyserver
        - name: cluster-proxy-service-ca
          configMap:
            defaultMode: 420
            name: openshift-service-ca.crt
