apiVersion: v1
kind: Service
metadata:
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": ocm-webhook
  labels:
    app: ocm-webhook
  name: ocm-webhook
  namespace: open-cluster-management
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8000
  selector:
    app: ocm-webhook
  type: ClusterIP
