// Copyright (c) 2020 Red Hat, Inc.
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/stolostron/multicloud-operators-foundation/pkg/proxyserver/apis/proxy/v1beta1/generated.proto

package v1beta1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *ClusterStatus) Reset()      { *m = ClusterStatus{} }
func (*ClusterStatus) ProtoMessage() {}
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098604adc36efcb, []int{0}
}
func (m *ClusterStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClusterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStatus.Merge(m, src)
}
func (m *ClusterStatus) XXX_Size() int {
	return m.Size()
}
func (m *ClusterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStatus proto.InternalMessageInfo

func (m *ClusterStatusList) Reset()      { *m = ClusterStatusList{} }
func (*ClusterStatusList) ProtoMessage() {}
func (*ClusterStatusList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098604adc36efcb, []int{1}
}
func (m *ClusterStatusList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterStatusList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClusterStatusList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStatusList.Merge(m, src)
}
func (m *ClusterStatusList) XXX_Size() int {
	return m.Size()
}
func (m *ClusterStatusList) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStatusList.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStatusList proto.InternalMessageInfo

func (m *ClusterStatusProxyOptions) Reset()      { *m = ClusterStatusProxyOptions{} }
func (*ClusterStatusProxyOptions) ProtoMessage() {}
func (*ClusterStatusProxyOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098604adc36efcb, []int{2}
}
func (m *ClusterStatusProxyOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterStatusProxyOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClusterStatusProxyOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStatusProxyOptions.Merge(m, src)
}
func (m *ClusterStatusProxyOptions) XXX_Size() int {
	return m.Size()
}
func (m *ClusterStatusProxyOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStatusProxyOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStatusProxyOptions proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClusterStatus)(nil), "github.com.open_cluster_management.multicloud_operators_foundation.pkg.proxyserver.apis.proxy.v1beta1.ClusterStatus")
	proto.RegisterType((*ClusterStatusList)(nil), "github.com.open_cluster_management.multicloud_operators_foundation.pkg.proxyserver.apis.proxy.v1beta1.ClusterStatusList")
	proto.RegisterType((*ClusterStatusProxyOptions)(nil), "github.com.open_cluster_management.multicloud_operators_foundation.pkg.proxyserver.apis.proxy.v1beta1.ClusterStatusProxyOptions")
}

func init() {
	proto.RegisterFile("github.com/stolostron/multicloud-operators-foundation/pkg/proxyserver/apis/proxy/v1beta1/generated.proto", fileDescriptor_a098604adc36efcb)
}

var fileDescriptor_a098604adc36efcb = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0xd1, 0xb1, 0x6f, 0xd3, 0x4e,
	0x14, 0x07, 0x70, 0xbb, 0xbf, 0x56, 0xbf, 0xe2, 0x52, 0x09, 0x3c, 0x95, 0x0c, 0xd7, 0x28, 0x53,
	0x17, 0xdf, 0x91, 0x0a, 0x21, 0x16, 0x96, 0x30, 0x21, 0x81, 0x5a, 0x85, 0x0d, 0x21, 0x85, 0x8b,
	0xf3, 0x6a, 0x1f, 0xc9, 0xf9, 0x8e, 0xbb, 0x77, 0x11, 0xdd, 0xf8, 0x07, 0x90, 0x58, 0xf9, 0x8f,
	0x32, 0x76, 0xec, 0x54, 0x11, 0xf3, 0x8f, 0xa0, 0x3b, 0x9b, 0x3a, 0xa1, 0x42, 0x62, 0x62, 0xf3,
	0x3d, 0xdf, 0x7b, 0x9f, 0xf7, 0xb5, 0x13, 0x57, 0x08, 0x2c, 0xdd, 0x94, 0xe6, 0x4a, 0x32, 0xa5,
	0xa1, 0xca, 0xf2, 0x85, 0xb3, 0x08, 0x26, 0x93, 0xbc, 0xe2, 0x05, 0x48, 0xa8, 0x90, 0x49, 0xb7,
	0x40, 0x91, 0x2f, 0x94, 0x9b, 0x65, 0x4a, 0x83, 0xe1, 0xa8, 0x8c, 0xcd, 0x2e, 0x94, 0xab, 0x66,
	0x1c, 0x85, 0xaa, 0x98, 0x9e, 0x17, 0x4c, 0x1b, 0xf5, 0xe9, 0xd2, 0x82, 0x59, 0x82, 0x61, 0x5c,
	0x0b, 0xdb, 0x14, 0xd8, 0x72, 0x38, 0x05, 0xe4, 0x43, 0x56, 0x40, 0xe5, 0x1b, 0x61, 0x46, 0xb5,
	0x51, 0xa8, 0x52, 0xe8, 0x58, 0xea, 0xd9, 0x49, 0xcb, 0x4e, 0x3a, 0x96, 0x76, 0xec, 0xe4, 0x96,
	0x9d, 0x74, 0x2c, 0xd5, 0xf3, 0x82, 0x6e, 0xb0, 0xd4, 0xb3, 0x4d, 0x81, 0xb6, 0x6c, 0x2f, 0xdb,
	0x48, 0x57, 0xa8, 0x42, 0xb1, 0xa0, 0x4f, 0xdd, 0x45, 0x38, 0x85, 0x43, 0x78, 0x6a, 0xb6, 0xea,
	0x3d, 0x99, 0x3f, 0xb3, 0x54, 0x28, 0x1f, 0x40, 0xf2, 0xbc, 0x14, 0x15, 0x98, 0xcb, 0x90, 0x2e,
	0x24, 0x92, 0x80, 0x9c, 0x2d, 0xef, 0x64, 0xe9, 0x3d, 0xfd, 0x53, 0x97, 0x71, 0x15, 0x0a, 0x09,
	0xcc, 0xe6, 0x25, 0x48, 0xfe, 0x7b, 0xdf, 0xe0, 0x63, 0x72, 0xf8, 0xa2, 0x49, 0xfd, 0x06, 0x39,
	0x3a, 0x9b, 0xbe, 0x4f, 0xf6, 0xbd, 0x31, 0xe3, 0xc8, 0x8f, 0xe2, 0x7e, 0x7c, 0x72, 0x70, 0xfa,
	0x98, 0x36, 0xb3, 0xe9, 0xe6, 0xec, 0x10, 0x3c, 0x84, 0xf5, 0xb7, 0xe9, 0x72, 0x48, 0xcf, 0xa6,
	0x1f, 0x20, 0xc7, 0xd7, 0x80, 0x7c, 0x94, 0xae, 0x6e, 0x8e, 0xa3, 0xfa, 0xe6, 0x38, 0xe9, 0x6a,
	0xe3, 0xdb, 0xa9, 0x83, 0x2f, 0x3b, 0xc9, 0xc3, 0x2d, 0xf3, 0x95, 0xb0, 0x98, 0xbe, 0xbb, 0xe3,
	0xd2, 0xbf, 0x73, 0x7d, 0x77, 0x50, 0x1f, 0xb4, 0xea, 0xfe, 0xaf, 0x4a, 0x67, 0xa6, 0xdf, 0xe2,
	0x64, 0x4f, 0x20, 0x48, 0x7b, 0xb4, 0xd3, 0xff, 0xef, 0xe4, 0xe0, 0x14, 0xe9, 0x3f, 0xf9, 0xf7,
	0x74, 0x2b, 0xe7, 0xe8, 0xb0, 0xdd, 0x70, 0xef, 0xa5, 0x5f, 0x65, 0xdc, 0x6c, 0x34, 0x78, 0x9e,
	0x3c, 0xda, 0xba, 0x76, 0xee, 0x27, 0x9c, 0x69, 0x4f, 0xd8, 0xb4, 0x9f, 0xec, 0x6a, 0x8e, 0x65,
	0xf8, 0x24, 0xf7, 0x46, 0xf7, 0xdb, 0x01, 0xbb, 0xe7, 0x1c, 0xcb, 0x71, 0x78, 0x33, 0xca, 0x56,
	0x6b, 0x12, 0x5d, 0xad, 0x49, 0x74, 0xbd, 0x26, 0xd1, 0xe7, 0x9a, 0xc4, 0xab, 0x9a, 0xc4, 0x57,
	0x35, 0x89, 0xaf, 0x6b, 0x12, 0x7f, 0xaf, 0x49, 0xfc, 0xf5, 0x07, 0x89, 0xde, 0xfe, 0xdf, 0x6e,
	0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x31, 0x99, 0x3d, 0x6c, 0x03, 0x00, 0x00,
}

func (m *ClusterStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClusterStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClusterStatusList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterStatusList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClusterStatusList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClusterStatusProxyOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterStatusProxyOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClusterStatusProxyOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Path)
	copy(dAtA[i:], m.Path)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Path)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClusterStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ClusterStatusList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *ClusterStatusProxyOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Path)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ClusterStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterStatus{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClusterStatusList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]ClusterStatus{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "ClusterStatus", "ClusterStatus", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&ClusterStatusList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClusterStatusProxyOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterStatusProxyOptions{`,
		`Path:` + fmt.Sprintf("%v", this.Path) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ClusterStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterStatusList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterStatusList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterStatusList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, ClusterStatus{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterStatusProxyOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterStatusProxyOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterStatusProxyOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
