//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1beta1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterStatus) OpenAPIModelName() string {
	return "com.github.stolostron.multicloud-operators-foundation.proxyserver.apis.proxy.v1beta1.ClusterStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterStatusList) OpenAPIModelName() string {
	return "com.github.stolostron.multicloud-operators-foundation.proxyserver.apis.proxy.v1beta1.ClusterStatusList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterStatusProxyOptions) OpenAPIModelName() string {
	return "com.github.stolostron.multicloud-operators-foundation.proxyserver.apis.proxy.v1beta1.ClusterStatusProxyOptions"
}
